# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_UV7HzoM-_c_hed7UFdSPHXtp3Ebh04
"""

print("Hello World!")

"""**Primer codigo realizado**"""